# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee59d947fadb9a910bd3b5c30e6f888ead3de0b9339575239e5430fb6d249477c7cae4033429dfe6747817632daf8796713d21f979b2ca5d0f28b2c559ee48c4

test:
  secret_key_base: be9ec2064d9d11cb94c1e97b511752d531791ca1912fd9f95f79560d187da1c00f4d2973f2e790230281a65afe85eb0f3b522c9cc9720ad8b3b2acdc2d1f78f9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
